name: lobi_application
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.2.1
  google_fonts: ^6.3.2
  google_sign_in: ^7.2.0
  intl: ^0.20.2
  lucide_icons: ^0.257.0
  lucide_icons_flutter: ^3.1.5
  pinput: ^5.0.2
  supabase_flutter: ^2.10.3
  url_launcher: ^6.3.2
  flutter_riverpod: ^2.6.1
  get_it: ^8.0.2
  logger: ^2.5.0
  flutter_screenutil: ^5.9.3
  soft_edge_blur: ^0.1.3
  progressive_blur: ^0.0.2
  liquid_glass_renderer: ^0.2.0-dev.2
  flutter_quill: ^11.5.0
  google_maps_flutter: ^2.14.0
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  http: ^1.6.0
  flutter_dotenv: ^6.0.0
  google_maps_flutter_ios: ^2.15.5
  image_picker: ^1.2.1
  permission_handler: ^12.0.1
  image_cropper: ^11.0.0
  animations: ^2.1.1
  mobile_scanner: ^7.1.3
  connectivity_plus: ^7.0.0
  pretty_qr_code: ^3.5.0
  firebase_core: ^4.2.1
  firebase_messaging: ^16.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.13

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
    - assets/images/parafoni-logo-dark.png
    - assets/images/system/lobi-icon.svg
    - assets/images/parafoni-login-img.png
    - assets/images/system/background-auth.png
    - assets/images/system/other-page-bg.png
    - assets/images/system/lobitext.svg
    - assets/images/system/parafoni-icon-logo-dark.svg
    - assets/images/system/google-icon.svg
    - assets/images/system/activity-cover-1.png
    - assets/images/system/activity-cover-2.png
    - assets/images/system/navigation/home-icon.svg
    - assets/images/system/navigation/discovery-icon.svg
    - assets/images/system/navigation/activity-icon.svg
    - assets/images/system/navigation/profile-icon.svg
    - assets/images/system/navigation/home-active-icon.svg
    - assets/images/system/navigation/discovery-active-icon.svg
    - assets/images/system/navigation/activity-active-icon.svg
    - assets/images/system/navigation/profile-active-icon.svg
    - assets/images/system/category/art-category-icon.svg
    - assets/images/system/category/concert-category-icon.svg
    - assets/images/system/category/film-category-icon.svg
    - assets/images/system/category/heart-category-icon.svg
    - assets/images/system/category/sport-category-icon.svg
    - assets/images/system/category/theater-category-icon.svg
    - assets/images/system/category/travel-category-icon.svg
    - assets/images/system/category/tech-category-icon.svg
    - assets/images/system/category/education-category-icon.svg
    - assets/images/system/category/food-category-icon.svg
    - assets/images/system/event-example.png
    - assets/images/system/event-example-white.png
    - assets/images/system/event-example-black.png
    - assets/images/system/event-example.png
    - assets/images/system/events_cover/events_cover_1.jpg
    - assets/images/system/events_cover/events_cover_2.jpg
    - assets/images/system/events_cover/events_cover_3.jpg
    - assets/images/system/events_cover/events_cover_4.jpg
    - assets/images/system/events_cover/events_cover_5.jpg
    - assets/images/system/events_cover/events_cover_6.jpg
    - assets/images/system/events_cover/events_cover_7.jpg
    - assets/images/system/events_cover/events_cover_8.jpg
    - assets/images/system/events_cover/events_cover_9.jpg
    - assets/images/system/events_cover/events_cover_10.jpg
    - assets/images/system/settings/setting-delete-icon.svg
    - assets/images/system/settings/setting-event-icon.svg
    - assets/images/system/settings/setting-lock-icon.svg
    - assets/images/system/settings/setting-qr-icon.svg
    - assets/images/system/settings/setting-question-icon.svg
    - assets/images/system/settings/setting-user-icon.svg
    - assets/images/system/settings/instagram.png
    - assets/images/system/settings/tiktok.png
    - assets/images/system/settings/youtube.png
    - assets/images/system/settings/web.png
    - assets/images/system/settings/linkedin.png
    - assets/images/system/profile-cover.png
  fonts:
    - family: Figtree
      fonts:
        - asset: assets/fonts/Figtree-Light.ttf
          weight: 300
        - asset: assets/fonts/Figtree-Regular.ttf
          weight: 400
        - asset: assets/fonts/Figtree-Medium.ttf
          weight: 500
        - asset: assets/fonts/Figtree-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Figtree-Bold.ttf
          weight: 700
        - asset: assets/fonts/Figtree-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Figtree-Black.ttf
          weight: 900

    - family: Urbanist
      fonts:
        - asset: assets/fonts/Urbanist-Regular.ttf
          weight: 400
        - asset: assets/fonts/Urbanist-Medium.ttf
          weight: 500
        - asset: assets/fonts/Urbanist-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Urbanist-Bold.ttf
          weight: 700
        - asset: assets/fonts/Urbanist-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Urbanist-Black.ttf
          weight: 900
