name: lobi_application
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.2.1
  google_fonts: ^6.3.2
  google_sign_in: ^7.2.0
  intl: ^0.20.2
  lucide_icons: ^0.257.0
  lucide_icons_flutter: ^3.1.5
  pinput: ^5.0.2
  supabase_flutter: ^2.10.3
  url_launcher: ^6.3.2
  flutter_riverpod: ^2.6.1
  get_it: ^8.0.2
  logger: ^2.5.0
  flutter_screenutil: ^5.9.3
  soft_edge_blur: ^0.1.3
  progressive_blur: ^0.0.2
  liquid_glass_renderer: ^0.2.0-dev.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.13

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/parafoni-logo-dark.png
    - assets/images/system/lobi-icon.svg
    - assets/images/parafoni-login-img.png
    - assets/images/system/background-auth.png
    - assets/images/system/other-page-bg.png
    - assets/images/system/parafoni-icon-logo-dark.svg
    - assets/images/system/google-icon.svg
    - assets/images/system/activity-cover-1.png
    - assets/images/system/activity-cover-2.png
  fonts:
    - family: Figtree
      fonts:
        - asset: assets/fonts/Figtree-Light.ttf
          weight: 300
        - asset: assets/fonts/Figtree-Regular.ttf
          weight: 400
        - asset: assets/fonts/Figtree-Medium.ttf
          weight: 500
        - asset: assets/fonts/Figtree-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Figtree-Bold.ttf
          weight: 700
        - asset: assets/fonts/Figtree-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Figtree-Black.ttf
          weight: 900
